check-for-app-update: false
external-sources:
  enable: false
db:
  auto-update: false
  validate-by-hash-on-start: true
  validate-age: true
  max-allowed-built-age: 120h
  require-update-check: false
